dist: trusty
language: ruby
sudo: false
rvm:
- 2.5.3
script: bundle exec rake test
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
branches:
  only:
  - gh-pages
addons:
  apt:
    packages:
    - libcurl4-openssl-dev
