markdown: kramdown
kramdown:
  toc_levels: "1..2"
  input: GFM
baseurl: /etc
plugins:
  - jekyll-sitemap
  - jekyll-redirect-from
  - jekyll-github-metadata
exclude: [vendor]
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"
name: Ryan Baumann - /etc
description: blog, wiki, miscellany, et cetera
url: https://ryanfb.github.io
repository: ryanfb/etc
sitemap:
  changefreq: daily
