markdown: kramdown
kramdown:
  toc_levels: "1..2"
  input: GFM
baseurl: /etc
plugins:
  - jekyll-sitemap
  - jekyll-redirect-from
  - jekyll-github-metadata
  - jekyll-seo-tag
  - jekyll-remote-theme
exclude: [vendor]
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"
      image: https://www.gravatar.com/avatar/5c60848658ff9b47c42196635fe0449b.jpg
title: /etc
description: blog, wiki, miscellany, et cetera
url: https://ryanfb.github.io
repository: ryanfb/etc
sitemap:
  changefreq: daily
remote_theme: ryanfb/jekyll-theme-palaios
citation_type: blog
donation_url: https://ryanfb.github.io/etc/tip-jar
author:
  name: Ryan Baumann
  first_name: Ryan
  last_name: Baumann
  email: ryan.baumann@gmail.com
  twitter: ryanfb
twitter:
  username: ryanfb
  card: summary
