markdown: kramdown
kramdown:
  input: GFM
baseurl: /etc
gems:
  - jekyll-sitemap
  - jekyll-redirect-from
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"
name: Ryan Baumann - /etc
description: blog, wiki, miscellany, et cetera
url: https://ryanfb.github.io
