markdown: kramdown
kramdown:
  input: GFM
baseurl: /etc
gems:
  - jekyll-last-modified-at
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"
