markdown: kramdown
kramdown:
  toc_levels: "1..2"
  input: GFM
baseurl: /etc
plugins:
  - jekyll-sitemap
  - jekyll-redirect-from
  - jekyll-github-metadata
  - jekyll-seo-tag
  - jekyll-remote-theme
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"
      image: https://ryanfb.xyz/logo.png
title: /etc
description: blog, wiki, miscellany, et cetera
url: https://ryanfb.xyz
repository: ryanfb/etc
sitemap:
  changefreq: daily
remote_theme: ryanfb/jekyll-theme-palaios
citation_type: blog
donation_url: https://ryanfb.xyz/etc/tip-jar
author:
  name: Ryan Baumann
  first_name: Ryan
  last_name: Baumann
  email: ryan.baumann@gmail.com
twitter:
  username: ryanfb
  card: summary
